name: Feature
description: Abstract feature description
title: "FEAT:"
projects: "BinaryStudioAcademy/bsa-2024-outreachvids"
body:
  - type: textarea
    id: what-feature
    attributes:
      label: What feature?
      placeholder: Add descriptions
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      placeholder: Add screenshots, mockups, etc.
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      placeholder: Add acceptance criteria.
